import Head from 'next/head';

export default function About() {
  return (
    <>
      <Head>
        <title>About | Ryan Leichty</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <article className='grid grid-cols-12 gap-4'>
        <h1 className='text-6xl'>About</h1>
      </article>
    </>
  );
}
