import Head from 'next/head';

function HiMark() {
  return 'Hi';
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Ryan Leichty</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className='mt-auto font-extralight text-[12.5vw] leading-[1.15]'>
        Designer <em>and</em> Coder
      </h1>
    </>
  );
}
