import Head from 'next/head';

export default function Uses() {
  return (
    <>
      <Head>
        <title>Uses | Ryan Leichty</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className='text-6xl'>Uses</h1>
    </>
  );
}
